### ISSUE TITLE
Limits on minimum word length are not respected by stemmers 1 and 2

### ISSUE THREAD

**Issue by Trey314159** [vukbatanovic/SCStemmers#2]
The limits in [stemDual1Word](https://github.com/vukbatanovic/SCStemmers/blob/master/src/weka/core/stemmers/KeseljSipkaStemmer.java#L45) for stemmers 1 and 2 are not being applied when the stemmer is **run from the command line.**

Words like baca, bena, beno, cima, demo, deni, dete, dnem, erem, este, gama, goste, hove, iste, ivan, ivana and others that match suffixes in the rules are being stemmed to nothing by stemmer 1. Stemmer 2 is a little less aggressive.

Similarly, all of these words are stemmed to just "p" by stemmer 1 (stemmer 2 is a bit less aggressive): p, paba, paca, paja, paka, past, pega, pekao, pela, pele, pena, peni, pete, peti, peć, peći, pijem, piju, pila, pile, piliće, pima, pisala, pisali, pisalo, pisan, pisana, pisane, pisani, pisao, pisati, pismo, pite, piti, piće, piše, pišući, poste, pula, puli, pune, puste, puta, pute, puti, puto, puše, п, пава, пади, пака, паст, пата, пајa, паја, пева, пега, пегле, пекао, пела, пеле, пели, пени, пено, пете, пети, пећ, пећи, пила, пиле, пили, пилиће, пило, пирели, писала, писале, писали, писало, писан, писана, писане, писани, писано, писао, писати, писах, писаше, писаће, писаћу, писмо, писте, пите, пити, пише, пишем, пишеш, пишући, пијем, пијемо, пијеш, пију, пиће, пићу, плац, плаца, плима, плиће, пому, поци, поче, птит, пула, пуле, пули, пуне, пусте, пута, путе, пути, путо, пучем.

**Comment by vukbatanovic** [comment]
You misread the code - the code lines that you refer to do not limit the length of the suffix that is to be removed. Instead, they prevent stemmers 1, 2 and 3 from processing any word which is shorter than 3 characters in the dual1 coding system.

As you have pointed out, this means that if an entire word is found in the suffix removal rule list, it can be reduced to nothing. This is, of course, not desirable, but the original purpose of this package was not to improve the existing stemming algorithms for Serbian or to introduce new ones, but rather to implement all of them under a single unified framework in order to easily perform extrinsic/intrinsic evaluations of their quality.

If you wish to create a novel algorithm or to correct some deficiencies in the rules of the existing ones, I would be happy to include your new/improved stemmer as a separate option within the package.

NB: I saw in your [notes](https://www.mediawiki.org/wiki/User:TJones_(WMF)/Notes/Serbian_Stemmer_Analysis) that you ignored stemmer 4 since "it is for Croatian". I nevertheless recommend that you take a look at it - Croatian and Serbian have extremely similar morphologies and my extrinsic evaluations on a few semantic tasks have found stemmer 4 to be superior to the first three. Of course, as always, your mileage may vary.

**Comment by Trey314159** [comment]
Thanks for the info! I only glanced at the code, looking for an obvious possible source of the problem, so I'm not surprised that I misread it.

How would you feel about a additional parameter for minimum stem length? It seems wasteful to re-implement existing stemmers to only change that one thing. Setting the minimum length to 0 (which could be the default) would give you the current behavior, and setting it to >0 would allow users to adjust the aggressiveness of the stemming based on their application.

It's good to hear your assessment of the Croatian stemmer—I was planning to evaluate it on some text from the Croatian Wikipedia and Wiktionary. The problem with using it for Serbian is that Serbian wikis are largely written in Cyrillic. If you think it is a better stemmer, I will wrap a Cyrillic-to-Latin converter around it and try it on Serbian. Since I hadn't see any indication of relative quality of the stemmers, I didn't consider the one labeled for "Croatian" for Serbian Cyrillic. Thanks for the tip!

**Comment by vukbatanovic** [comment]
I have added a cyrillic to latin script preprocessing step to the Ljubešić & Pandžić (Croatian) stemmer, so you should be able to evaluate it now. In case you still find one of the first three stemmers to be better, we can add the minimum stem length feature that you propose.

**Comment by Trey314159** [comment]
That's great news—thanks! I'll put it through its paces in the next couple of days and see how it goes. If you are available to review the results (similar to my notes you already looked at), let me know and I'll send you a link when it's ready.

**Comment by vukbatanovic** [comment]
Sure, I'll take a look, just let me know when you're finished!
